apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  type: service
  applicationContainers: []
  minReplicas: 1
  maxReplicas: 5
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: my-node-name
  serviceType: LoadBalancer
  namespace: foo
  suspend: false
  ttlSecondsAfterFinished: 0
  name: mist
  labels:
    app: westeros
    env: production
    applicationId: project_97d17baf-7c2e-41be-af10-7b01da502abe
    projectId: project_1721eeda-2824-4f3c-b0c0-3ec047e465b5
    organizationId: org_01b50229-db34-43d4-8f3e-d1aeb683d900
    environmentId: env_904257f0-f5ac-4185-8ecd-25520d4b53ba
    environmentName: dev
  horizontalAutoScalingRules:
    - ruleType: cpu
      percentage: 80
  volumes:
    - name: my-volume
      type: PersistentVolumeClaim
      pvc:
        claimName: my-claim
