apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: johnsnow
    application-id: project_cabb7b3b-eca3-4b10-8e7a-3ffad4ac9329
  name: johnsnow
spec:
  selector:
    app: johnsnow
