apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: praisethelord
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: praisethelord
