apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      container:
        image:  kustomize_dev:1.0.0
spec:
  applicationContainers:
    - imageTag: 1.22.0
      cpuRequestMili: 100
      cpuLimitMili: 200
      memoryRequestMb: 100
      memoryLimitMb: 200
      command:
        - hello
        - world
      applicationPorts:
        - port: 80
          protocol: TCP
      healthChecks:
        - httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          probeType:
            - readinessProbe
            - livenessProbe
      name: main-container
      imageRegistry: test
    - name: second-container
      imageRegistry: second
      imageTag: 1.22.0
      cpuRequestMili: 100
      cpuLimitMili: 200
      memoryRequestMb: 100
      memoryLimitMb: 200
      command:
        - hello3
        - world2
      applicationPorts:
        - port: 3000
          protocol: TCP
        - port: 8081
          protocol: TCP
      configMounts:
        - secretName: secret-file
          mountPath: /etc/config/file.txt
          isFile: true
          key: file.txt
        - configMapName: config-dir
          mountPath: /etc/config/some-path
          isFile: false
  minReplicas: 20
  maxReplicas: 6
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: true
  labels:
    app: test
    jackson: reddit
  horizontalAutoScalingRules:
    - ruleType: cpu
      percentage: 100
    - ruleType: memory
      percentage: 80
  type: service
  serviceType: ClusterIP
  namespace: test
  name: app-name
  cronTab: ''
